-- =============================================================================
-- supabase/schema.sql
-- Database Schema สำหรับ Supabase (PostgreSQL)
-- ระบบ POS ร้านยำ (Yum2K) 
-- นำโค้ดนี้ไปรันใน SQL Editor ของ Supabase Dashboard
-- =============================================================================

-- ==========================================
-- 1. ลบ Table เก่า (ถ้ามี) - เพื่อให้รันซ้ำได้
-- ==========================================
DROP TABLE IF EXISTS sync_queue;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS profiles;

-- ==========================================
-- 2. สร้างตาราง Categories (หมวดหมู่สินค้า)
-- ==========================================
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  icon_url TEXT,
  color TEXT,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 3. สร้างตาราง Products (สินค้า)
-- ==========================================
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  sku TEXT,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  sale_price NUMERIC(10, 2) NOT NULL,
  cost_price NUMERIC(10, 2) NOT NULL,
  stock_quantity INTEGER DEFAULT 0,
  alert_threshold INTEGER DEFAULT 10,
  track_inventory BOOLEAN DEFAULT TRUE,
  mapping_type TEXT, -- 'bundle', 'promotion', 'variant'
  inventory_mappings JSONB, -- เก็บ JSON Array ของการตัดสต็อก 
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 4. สร้างตาราง Profiles (พนักงาน)
-- (ผูกกับ auth.users ของ Supabase)
-- ==========================================
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'staff')),
  pin TEXT, -- PIN 4 หลัก สำหรับ Tablet
  avatar_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_deleted BOOLEAN DEFAULT FALSE,
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 5. สร้างตาราง Orders (ออร์เดอร์หลัก)
-- ==========================================
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE,
  order_number TEXT NOT NULL UNIQUE,
  staff_id UUID REFERENCES profiles(id) ON DELETE SET NULL, -- ใครเป็นคนขาย
  staff_name TEXT NOT NULL, -- Snapshot ชื่อพนักงาน ณ เวลาขาย
  subtotal NUMERIC(10, 2) NOT NULL,
  discount_amount NUMERIC(10, 2) DEFAULT 0,
  tax_rate NUMERIC(5, 2) DEFAULT 0,
  tax_amount NUMERIC(10, 2) DEFAULT 0,
  total_amount NUMERIC(10, 2) NOT NULL,
  total_cost NUMERIC(10, 2) NOT NULL,
  profit_amount NUMERIC(10, 2) NOT NULL,
  payment_method TEXT NOT NULL,
  amount_received NUMERIC(10, 2) NOT NULL,
  change_amount NUMERIC(10, 2) NOT NULL,
  status TEXT NOT NULL,
  note TEXT,
  delivery_ref TEXT,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 6. สร้างตาราง Order Items (รายละเอียดออร์เดอร์)
-- แบบ Normalization (แยก Table ไม่ได้เก็บ JSONB ก้อนเดียวเหมือน Local DB)
-- ==========================================
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL, -- Snapshot ชื่อสินค้า
  product_sku TEXT, -- Snapshot SKU
  quantity INTEGER NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  cost_price NUMERIC(10, 2) NOT NULL,
  discount NUMERIC(10, 2) DEFAULT 0,
  total_price NUMERIC(10, 2) NOT NULL,
  inventory_deductions JSONB, -- Snapshot ว่าตอนนั้นตัดสต็อกสินค้าหลักอะไรไปบ้าง
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 7. สร้าง Row Level Security (RLS) - ความปลอดภัยเบื้องต้น
-- ==========================================
-- เปิดใช้งาน RLS ทุก Table
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- สร้าง Policy ให้ Anonymous (anon) และ Auth Users อ่าน/เขียนข้อมูลได้ (สำหรับการทดสอบระบบ Sync)
-- หมายเหตุ: ควรปรับเป็นแบบ Authenticated-only เมื่อมีระบบ Login สมบูรณ์
CREATE POLICY "อนุญาตให้ทุกคนเข้าถึง categories ได้" ON categories FOR ALL TO public USING (true);
CREATE POLICY "อนุญาตให้ทุกคนเข้าถึง products ได้" ON products FOR ALL TO public USING (true);
CREATE POLICY "อนุญาตให้ทุกคนเข้าถึง profiles ได้" ON profiles FOR ALL TO public USING (true);
CREATE POLICY "อนุญาตให้ทุกคนเข้าถึง orders ได้" ON orders FOR ALL TO public USING (true);
CREATE POLICY "อนุญาตให้ทุกคนเข้าถึง order_items ได้" ON order_items FOR ALL TO public USING (true);

-- (Optional) อนุญาตให้อ่าน Categories, Products ได้แม้ไม่ Login
CREATE POLICY "อนุญาตอ่าน categories แบบสาธารณะ" ON categories FOR SELECT TO public USING (true);
CREATE POLICY "อนุญาตอ่าน products แบบสาธารณะ" ON products FOR SELECT TO public USING (true);
